[package]
name = "rts-game"
version = "0.1.0"
edition = "2021"
license = "GPL-3"

[dependencies]
bevy = "0.12.1"
rand = "0.8"
winit = "0.28"
image = "0.24"
bevy-inspector-egui = "0.22.1"

[workspace]
resolver = "2"