[package]
name = "rts-game"
version = "0.1.0"
edition = "2021"
license = "GPL-3"

[dependencies]
bevy = "0.13.0"
rand = "0.8"
winit = "0.29.10"
image = "0.24"
bevy-inspector-egui = "0.22.1"
bevy_rapier2d = "0.25.0"
lazy_static = "1.5.0"

[workspace]
resolver = "2"
